openapi: 3.0.1
info:
  title: Microsoft Sentinel - Incident Comments
  version: "1.0.0"
  description: |
    API for retrieving comments from Microsoft Sentinel incidents.
    #ExamplePrompts Show comments for Sentinel incident 456
    #ExamplePrompts Get incident comments for incident ABC123
    #ExamplePrompts Retrieve all comments for a Sentinel incident
    #ExamplePrompts List comments for a specific incident in Sentinel

servers:
  - url: https://management.azure.com

paths:
  /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.OperationalInsights/workspaces/{workspaceName}/providers/Microsoft.SecurityInsights/incidents/{incidentId}/comments:
    get:
      operationId: GetIncidentComments
      summary: Retrieve comments for a Sentinel incident.
      description: |
        Fetches all comments associated with a given Microsoft Sentinel incident.
        Useful for investigation context and analyst collaboration.
        #ExamplePrompts Show Sentinel incident comments
        #ExamplePrompts Get comments for incident {incidentId}

      parameters:
        - in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          description: Azure Subscription ID.

        - in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
          description: Resource group name.

        - in: path
          name: workspaceName
          required: true
          schema:
            type: string
          description: Workspace name.

        - in: path
          name: incidentId
          required: true
          schema:
            type: string
          description: The ID of the Sentinel incident.

        - in: query
          name: api-version
          required: true
          schema:
            type: string
            default: "2023-11-01-preview"
          description: Azure API version.

      responses:
        "200":
          description: Successfully retrieved incident comments.
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        properties:
                          type: object
                          properties:
                            message:
                              type: string
                            author:
                              type: string
                            createdTimeUtc:
                              type: string
                              format: date-time
        "401":
          description: Unauthorized (AAD authentication required)
        "404":
          description: Incident not found.
