openapi: 3.0.1
info:
  title: Microsoft Sentinel - Incident Comments
  version: "1.0.0"
  description: API to retrieve comments for a Sentinel Incident.

servers:
  - url: https://management.azure.com

paths:
  /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.OperationalInsights/workspaces/{workspaceName}/providers/Microsoft.SecurityInsights/incidents/{incidentId}/comments:
    get:
      operationId: GetIncidentComments
      summary: Retrieve comments for a Sentinel incident.
      description: Returns a list of comments associated with the specified Microsoft Sentinel incident.
      parameters:
        - in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          description: Azure Subscription ID.

        - in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
          description: Resource group name.

        - in: path
          name: workspaceName
          required: true
          schema:
            type: string
          description: Workspace name (Log Analytics workspace).

        - in: path
          name: incidentId
          required: true
          schema:
            type: string
          description: ID of the Sentinel incident.

        - in: query
          name: api-version
          required: true
          schema:
            type: string
            default: "2023-11-01-preview"
          description: API version.

      responses:
        "200":
          description: Successfully retrieved incident comments.
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: Comment ID.
                        properties:
                          type: object
                          properties:
                            message:
                              type: string
                              description: Text content of the comment.
                            author:
                              type: string
                              description: Who added the comment.
                            createdTimeUtc:
                              type: string
                              format: date-time
                              description: When the comment was created.
        "401":
          description: Authentication failure.
        "404":
          description: Incident not found.
