openapi: 3.0.0
info:
  title: Shodan Security API
  description: Complete Shodan API specification for security scanning and intelligence gathering.
  version: 1.0.0
servers:
  - url: https://api.shodan.io

paths:
  /shodan/host/{ip}:
    get:
      operationId: getHostInfo
      summary: Get detailed information for a specific host.
      parameters:
        - in: path
          name: ip
          schema:
            type: string
          required: true
          example: "8.8.8.8"
      responses:
        '200':
          description: Host information retrieved successfully.
        '400':
          description: Invalid IP address.
        '401':
          description: Invalid API key.
        '403':
          description: Requires membership or higher to access.
        '404':
          description: Host not found.

  /shodan/ports:
    get:
      operationId: listPorts
      summary: List all ports that Shodan is currently crawling on the Internet.
      responses:
        '200':
          description: Ports list retrieved successfully.
        '401':
          description: Invalid API key.

  /shodan/host/count:
    get:
      operationId: countHosts
      summary: Get the total number of results that matched a query (without returning results).
      parameters:
        - in: query
          name: query
          schema:
            type: string
          required: true
          example: "apache"
      responses:
        '200':
          description: Count retrieved successfully.
        '401':
          description: Invalid API key.

  /shodan/host/search:
    get:
      operationId: searchHosts
      summary: Search Shodan using website-like query syntax.
      parameters:
        - in: query
          name: query
          schema:
            type: string
          required: true
          example: "nginx country:US"
      responses:
        '200':
          description: Search results retrieved successfully.
        '401':
          description: Invalid API key.

  /shodan/protocols:
    get:
      operationId: listProtocols
      summary: List all protocols that can be used when launching an Internet scan.
      responses:
        '200':
          description: Protocols retrieved successfully.
        '401':
          description: Invalid API key.
